name: haptic_image_teacher_aware

image_shape: &image_shape [3, 640, 480]
shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    usb_cam_right:
      shape: *image_shape
      type: rgb
    usb_cam_left:
      shape: *image_shape
      type: rgb
    usb_cam_table:
      shape: *image_shape
      type: rgb
    left_smarty_arm_output:
      shape: [7] # just pose
      type: low_dim
    right_smarty_arm_output:
      shape: [7] # just pose
      type: low_dim
    rdda_right_obs:
      shape: [9]
      type: low_dim
    rdda_left_obs:
      shape: [9]
      type: low_dim

  action:
    shape: [26]
    # addition here - rdda_right_act (6)[wave, pos_d] + rdda_left_act(6) [wave, pos_d] + left_smarty_arm_pose(7) 
    # + right_smarty_arm_pose(7) 

task_name: &task_name bottle_pick
dataset_type: &dataset_type 
dataset_path: &dataset_path  /home/ali/shared_volume/processed_bottle_pick_data/finer/teacher_aware_out_zarr
abs_action: &abs_action False

dataset:
  _target_: diffusion_policy.dataset.robomimic_replay_image_dataset.RobomimicReplayImageDataset
  shape_meta: *shape_meta
  dataset_path: *dataset_path
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  abs_action: *abs_action
  rotation_rep: 'rotation_6d'
  use_legacy_normalizer: False
  use_cache: True
  seed: 42
  val_ratio: 0.02
